name: test
on: push

jobs:
  unit tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Gradle Test
        run: |
          chmod +x gradlew
          ./gradlew test

      - name: Publish Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/test-results/**/*.xml
